#!/bin/bash
#
#chkconfig: 235 99 01
#description: Starts and stops ServerUsage-Client

#==============================================================================+
# File name   : serverusage_client
# Begin       : 2012-04-12
# Last Update : 2012-08-21
# Version     : 6.3.2
#
# Description : Init script to execute ServerUsage-Client-MDB.
#
# Website     : https://github.com/fubralimited/ServerUsage
#
# Author: Nicola Asuni
#
# (c) Copyright:
#               Fubra Limited
#               Manor Coach House
#               Church Hill
#               Aldershot
#               Hampshire
#               GU12 4RQ
#               UK
#               http://www.fubra.com
#               support@fubra.com
#
# License:
#		Copyright (C) 2012-2012 Fubra Limited
#
#		This program is free software; you can redistribute it and/or modify
# 		it under the terms of the GNU General Public License as published by
# 		the Free Software Foundation; version 2 of the License.
#
# 		This program is distributed in the hope that it will be useful,
# 		but WITHOUT ANY WARRANTY; without even the implied warranty of
# 		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# 		GNU General Public License for more details.
#
# 		You should have received a copy of the GNU General Public License along
# 		with this program; if not, write to the Free Software Foundation, Inc.,
# 		51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# 		See LICENSE.TXT file for more information.
#==============================================================================+

# configuration file
CONFIG_FILE="/etc/serverusage_client_mdb.conf"

# load parameters from configuration file
if [ -f $CONFIG_FILE ] ; then
	. $CONFIG_FILE
fi

# check empty server ID
if [ -z "$SERVER_ID" ] ; then
	# set hostname
	SERVER_ID=`hostname`
fi

# command to execute
CMDMDB="$PATH_MDBCLIENT $LOGSERVER_IP $LOGSERVER_PORT $DATABASE_HOST $DATABASE_PORT $DATABASE_USER $DATABASE_PASSWORD $SAMPLING_TIME $SERVER_ID $PATH_TCPSENDER $PATH_TEMPLOG"

# get SystemV Init function library.
if [ -f /etc/init.d/functions ] ; then
	. /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
	. /etc/rc.d/init.d/functions
else
	exit 1
fi

# Start the service
start() {
	if test -f /var/lock/subsys/serverusage_client_mdb ; then
		# check if the process is running
		if [ ! -z "`ps ax | grep -v grep | grep $PATH_MDBCLIENT`" ]; then
			echo -n $"Service is Already Running."
			echo
			return
		else
			# delete the orphan lock file
			rm -f /var/lock/subsys/serverusage_client_mdb
		fi
	fi
	echo -n $"Starting ServerUsage-Client-MDB: "
	daemon $CMDMDB &
	# create the lock file
	touch /var/lock/subsys/serverusage_client_mdb
	success $"ServerUsage-Client-MDB startup"
	echo
}

# Restart the service
stop() {
	echo -n $"Stopping ServerUsage-Client-MDB: "
	# check if the process is running
	if [ ! -z "`ps ax | grep -v grep | grep $PATH_MDBCLIENT`" ]; then
		# kill the process
		killproc $PATH_MDBCLIENT
	else
		failure $"ServerUsage-Client-MDB stop"
	fi
	# delete the lock file
	rm -f /var/lock/subsys/serverusage_client_mdb
	echo
}

### main logic ###
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		status $PATH_MDBCLIENT
		;;
	restart|reload)
		stop
		start
		;;
	condrestart)
		if test -f /var/lock/subsys/serverusage_client_mdb ; then
			stop
			start
		fi
		;;
	*)
		echo $"Usage: $0 {start|stop|status|restart|reload|condrestart}"
		exit 1
esac

exit 0

#==============================================================================+
# END OF FILE
#==============================================================================+
