#!/bin/bash
#
#chkconfig: 235 99 01
#description: Starts and stops ServerUsage-Client

#==============================================================================+
# File name   : serverusage_client
# Begin       : 2012-04-12
# Last Update : 2013-03-19
# Version     : 6.3.8
#
# Description : Init script to execute ServerUsage-Client.
#
# Website     : https://github.com/fubralimited/ServerUsage
#
# Author: Nicola Asuni
#
# (c) Copyright:
#               Fubra Limited
#               Manor Coach House
#               Church Hill
#               Aldershot
#               Hampshire
#               GU12 4RQ
#               UK
#               http://www.fubra.com
#               support@fubra.com
#
# License:
#    Copyright (C) 2012-2012 Fubra Limited
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#    See LICENSE.TXT file for more information.
#==============================================================================+

# configuration file
CONFIG_FILE="/etc/serverusage_client.conf"

# load parameters from configuration file
if [ -f $CONFIG_FILE ] ; then
	. $CONFIG_FILE
fi

# check empty server ID
if [ -z "$SERVER_ID" ] ; then
	# set hostname
	SERVER_ID=`hostname`
fi

# commands to execute (systemtap monitoring + tcp sender)
CMDSTAP="$PATH_STAPRUN -b $BUFFER_SIZE $PATH_STAPMODULE smp=$SAMPLING_TIME srvid=$SERVER_ID"
CMDTCPS="$PATH_TCPSENDER $LOGSERVER_IP $LOGSERVER_PORT $PATH_TEMPLOG"
LOCKFILE="/var/lock/serverusage_client"
PID=`ps ax | grep -v grep | grep "$PATH_STAPIO" | awk '{print $1;}'`
PIDB=`ps ax | grep -v grep | grep "$PATH_TCPSENDER" | awk '{print $1;}'`
RETVAL=0

# get SystemV Init function library.
if [ -f /etc/init.d/functions ] ; then
	. /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
	. /etc/rc.d/init.d/functions
elif [ -f /lib/lsb/init-functions ] ; then
	. /lib/lsb/init-functions
else
	exit 1
fi

# Start the service
start() {
	echo -n "Starting ServerUsage-Client: "
	if test -f $LOCKFILE ; then
		# check if the process is running
		if [ ! -z "$PID" ] && [ ! -z "$PIDB" ]; then
			echo -n "Service is Already Running."
			echo
			return
		else
			# delete the orphan lock file
			rm -f $LOCKFILE
		fi
	fi
	(setsid bash -c "($CMDSTAP | $CMDTCPS) & disown %%") </dev/null >&/dev/null &
	RETVAL=$?
	[ $RETVAL = 0 ] && touch $LOCKFILE && echo "OK" || echo "ERROR"
	return $RETVAL
}

# Restart the service
stop() {
	echo -n "Stopping ServerUsage-Client: "
	# check if the process is running
	if [ ! -z "$PID" ]; then
		# kill the process
		kill $PID
		RETVAL=$?
		echo "OK"
	else
		RETVAL=3
		echo "Service is not running."
	fi
	if [ ! -z "$PIDB" ]; then
		# kill the process
		kill $PIDB
	fi
	rm -f $LOCKFILE
	return $RETVAL
}

### main logic ###
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		echo -n "ServerUsage-Client status: "
		if [ ! -z "$PID" ] && [ ! -z "$PIDB" ]; then
			RETVAL=0
			echo "Service is running."
		else
			if test -f $LOCKFILE ; then
				RETVAL=2
				echo "Service is dead and $LOCKFILE lock file exist."
			else
				RETVAL=3
				echo "Service is not running."
			fi
		fi
		;;
	restart|reload)
		stop
		start
		;;
	condrestart)
		if test -f $LOCKFILE ; then
			stop
			start
		fi
		;;
	*)
		echo "Usage: $0 {start|stop|status|restart|reload|condrestart}"
		RETVAL=2
		[ "$1" = 'usage' ] && RETVAL=0
esac
exit $RETVAL

#==============================================================================+
# END OF FILE
#==============================================================================+
