.\" Manpage for ServerUsage-Client.
.TH serverusage_client 8 "2012-08-29"
.SH NAME
serverusage_client \- ServerUsage-Client control interface
.SH SYNOPSIS
serverusage_client is a SysV init script that takes one-word commands, defined below:
.PP
.B serverusage_client
.I command
.PP
.SH DESCRIPTION
.B serverusage_client
is a front end to the ServerUsage-Client program.
The ServerUsage-Client program is composed by two main sections: the SystemTap
.B serverusage_client.ko
kernel module to collect and output usage statistics of the machine where it is installed, and
.B serverusage_tcpsender.bin
to send the output to a log server via TCP.
.PP
.B NOTE:
The configuration file is located at
.B /etc/serverusage_client.conf
.PP
.SH OPTIONS
The \fIcommand\fP can be any one of the following options:
.TP 14
.BI start
Start ServerUsage-Client (SystemTap serverusage_client.ko kernel module + serverusage_tcpsender.bin).
.TP
.BI stop
Stops ServerUsage-Client.
.TP
.BI restart
Restarts ServerUsage-Client.
If the program is not running, it is started.
.BI status
Displays a brief status report.
.BI help
Displays a short help message.
.SH AUTHOR
Nicola Asuni (nicola@fubra.com)
.SH COPYRIGHT
(c) 2012-2012 Fubra Limited
Manor Coach House, Church Hill, Aldershot, Hampshire, GU12 4RQ, UK (http://www.fubra.com - support@fubra.com)
.
